### ISSUE TITLE
Make this work on stable (and beta)?

### ISSUE THREAD

**Issue by Sh4rK** [japaric/panic-abort#5]
`panic_handler` is now stable (at least on 1.31-beta), but this crate also requires `core::intrinsics::abort` which is nightly-only. Can we replace it with something to make this crate stable? What does abort do anyway on a microcontroller?

**Comment by jonas-schievink** [comment]
`intrinsics::abort()` [lowers to the `llvm.trap` intrinsic](https://github.com/rust-lang/rust/blob/7fdea7a72abb9f5a58fdc19c0a298042291c53b2/src/librustc_codegen_llvm/intrinsic.rs#L712-L715), which LLVM [lowers to a `0xdefe` instruction, or `udf #254`](https://github.com/llvm/llvm-project/blob/1a219aa8df9b4f58e6dbf7beadf1316eb3c5b2f8/llvm/lib/Target/ARM/ARMInstrThumb.td#L656-L661).

The same could be accomplished with external assembly, but would probably result in the panic info not being optimized out as it gets now.
