### ISSUE TITLE
Does this reset the processor, or stop the processor?

### ISSUE THREAD

**Issue by riaqn** [japaric/panic-abort#6]
As the title says, I wonder if `abort` will reset the processor or stop the processor?

I also wonder how this interacts with independent watchdog?

Thank you.

**Comment by japaric** [comment]
I forget that `intrinsics::abort` is not documented at all in the standard library. See PR #7.

> I also wonder how this interacts with independent watchdog?

Unless the watchdog is specified in the ISA, the answer is the behavior is device dependent (i.e. whatever the vendor implemented).
